export enum ActionTypes {
  CAMPAIGN_NEW = '[Campaign] Campaign New',
  CAMPAIGN_LOAD_OPTIONS = '[Campaign] Campaign Load Options',
  CAMPAIGN_LOAD = '[Campaign] Campaign Load',
  CAMPAIGN_LOAD_SUCCESS = '[Campaign] Campaign Load Success',
  CAMPAIGN_LOAD_FAILURE = '[Campaign] Campaign Load Failure',
  CAMPAIGN_FORM_UPDATE = '[Campaign] Campaign Form Update',
  CAMPAIGN_SET_ADVERTISER = '[Campaign] Campaign Set Advertiser',
  CAMPAIGN_SAVE = '[Campaign] Form Save',
  CAMPAIGN_SAVE_SUCCESS = '[Campaign] Form Save Success',
  CAMPAIGN_SAVE_FAILURE = '[Campaign] Form Save Failure',
  CAMPAIGN_ADD_FLIGHT = '[Campaign] Add Flight',
  CAMPAIGN_ADD_FLIGHT_WITH_TEMP_ID = '[Campaign] Add Flight With Temp Id',
  CAMPAIGN_DUP_FLIGHT = '[Campaign] Dup Flight',
  CAMPAIGN_DUP_FLIGHT_WITH_TEMP_ID = '[Campaign] Dup Flight With Temp Id',
  CAMPAIGN_DELETE_FLIGHT = '[Campaign] Delete Flight',
  CAMPAIGN_FLIGHT_FORM_UPDATE = '[Campaign] Flight Form Update',
  CAMPAIGN_FLIGHT_SET_GOAL = '[Campaign] Flight Set Goal',
  CAMPAIGN_ALLOCATION_PREVIEW_LOAD = '[Campaign] Allocation Preview Load',
  CAMPAIGN_ALLOCATION_PREVIEW_LOAD_SUCCESS = '[Campaign] Allocation Preview Load Success',
  CAMPAIGN_ALLOCATION_PREVIEW_LOAD_FAILURE = '[Campaign] Allocation Preview Load Failure',
  CAMPAIGN_AVAILABILITY_LOAD = '[Campaign] Availability Load',
  CAMPAIGN_AVAILABILITY_LOAD_SUCCESS = '[Campaign] Availability Load Success',
  CAMPAIGN_AVAILABILITY_LOAD_FAILURE = '[Campaign] Availability Load Failure'
}
